### ISSUE TITLE
Allow disabling generation in new chunks

### ISSUE THREAD

**Issue by masmc05** [MagmaGuy/BetterStructures#12]
https://spark.lucko.me/27z2oNxXZQ
it's laggy, and tps drops a lot because of this

**Comment by MagmaGuy** [comment]
You can do this by removing the plugin. If it is not generating builds in new chunks, then the plugin quite literally does not do anything at all.

I plan to release a rewrite which does not depend on worldguard / fawe for pasting, which is the heaviest operation the plugin does. However, it will always needs to scan new terrain for fits, since this is not a world generation plugin, and that is always going to put some extra load on new chunks.

You can also pregenerate the world to combat this.

**Comment by masmc05** [comment]
> You can do this by removing the plugin. If it is not generating builds in new chunks, then the plugin quite literally does not do anything at all.
> 
> I plan to release a rewrite which does not depend on worldguard / fawe for pasting, which is the heaviest operation the plugin does. However, it will always needs to scan new terrain for fits, since this is not a world generation plugin, and that is always going to put some extra load on new chunks.
> 
> You can also pregenerate the world to combat this.

wait, wasn't it generating in background before? just before this we always pregenerated the map and your plugin was still generating, we now don't do that because other than your plugin, nothing creates lags
