### ISSUE TITLE
(Suggestion) Region or Residence sign

### ISSUE THREAD

**Issue by AllayBreeze** [MagmaGuy/BetterStructures#8]
A special block type that can automatically create a region (from WorldGuard plugin) or residence (from Residence plugin) when the structure generates. Two region signs (with positions separately set to 1 and 2, and with same name and owners) represents two positions forming the region or residence.

**Formats:**

**[region]** or **[residence]** #first line, indicates that this is a region or residence sign.

**\<position\>** #second line, defines the position that a region or residence requires. Can be 1 or 2.

**\<name\>** #third line, defines the name of the region or residence. If a same name region or residence already exists, the name will be automatically added by a unique number suffix, such as "dungeon_1", "castle_222".

**\<owner\>** #last line, defines the owner of the region or residence.

**Comment by MagmaGuy** [comment]
This is partially planned as a part of the EliteMobs integration, some structures will get worldguard regions defined that will prevent players from editing blocks to make the combat easier, and once the boss is defeated the region will be removed and the area will be editable once again.

That being said, this will not be done through signs and I have no intention of adding any kind of "residence" system since I don't really see who would be assigned as the owner of a randomly generated structure or how that wouldn't cause vast amounts of issues such as not knowing that you have a structure, having other people stumble into randomly generated structures that aren't theirs near their own places, having one person generate vast amounts of space by exploring and subsequently having tens of thousands of structures assigned to them alone, to name a few.
